name: CI/CD Pipeline for Nginx

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-cd:
    runs-on: self-hosted

    steps:
      - name: Kodu Kontrol Et
        run: |
          echo "Kod başarıyla geldi."
          # Örneğin: YML syntax kontrolü
          yamllint /home/Pipeline/nginx-deployment.yaml || true

      - name: Nginx Deploy
        run: |
          cd /home/Pipeline
          kubectl apply -f nginx-deployment.yaml

      - name: Deploy Başarı Logu
        run: echo "NGINX otomatik deploy edildi: $(date)" >> /home/Pipeline/deploy.log
